### ISSUE TITLE
Cannot install and use

### ISSUE THREAD

**Issue by YvanYifeiLi** [wesbaker/alfred-goodreads-workflow#54]
Hello there maybe I'm dumb but I cannot install and use this package. 

There is no alfredworkflow extension so I cannot import it to my Alfred.

I've also tried installing via terminal and failed: [screenshot](https://i.imgur.com/BiqbZiw.png)

**Comment by wesbaker** [comment]
Looks like your install of npm has permissions issues. You could `sudo npm install ...` or you could dig into why the permissions aren’t working.
